components:
  schemas:
    Create:
      type: object
      properties:
        title:
          type: string
          description: title of the product
        price:
          type: number
          description: price of the product
        stock:
          type: number
          description: stock of the product
        photo:
          type: string
          description: photo of the product
        owner_id:
          type: string
          description: owner id of the product
      example:
        title: monitor
        price: 10000
        stock: 50
        photo: monitorurl
        owner_id: 94733a1b1a4e982dd7dab0e7
  responses:
    res201:
      description: Success response
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                description: Status code of the response
              response:
                type: object
                properties:
                  title:
                    type: string
                  price:
                    type: number
                  stock:
                    type: number
                  photo:
                    type: string
                  owner_id:
                    type: string
                  _id:
                    type: string
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
                  __v:
                    type: number
            example:
              statusCode: 201
              response:
                title: celular usado
                price: 200
                stock: 40
                photo: "https://jkfenner.com/wp-content/uploads/2019/11/default.jpg"
                owner_id: "2c6bc858a698c6c34e052c59"
                _id: "b415aa91412ee49ca816ae63"
                createdAt: "2024-05-09T18:06:32.746Z"
                updatedAt: "2024-05-09T18:06:32.746Z"
                __v: 0

    res401:
      description: Unauthorized response
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                description: Status code of the response
              message:
                type: string
                description: Error message
            example:
              statusCode: 401
              message: "Bad Auth!"

    res403:
      description: Forbidden response
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                description: Status code of the response
              message:
                type: string
                description: Error message
            example:
              statusCode: 403
              message: "Forbidden"

    res500:
      description: Internal Server Error response
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                description: Status code of the response
              message:
                type: string
                description: Error message
            example:
              statusCode: 500
              message: "POST /api/products/ products validation failed: title: Path `title` is required."

paths:
  /api/products:
    post:
      summary: to create a product
      tags:
        - Products
      requestBody:
        required: true
        description: data of the product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Create'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/responses/res201'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/responses/res401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/responses/res403'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/responses/res500'
