components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: title of the product
        price:
          type: number
          description: price of the product
        stock:
          type: number
          description: stock of the product
        photo:
          type: string
          description: photo of the product
        _id:
          type: string
          description: id of the product
        owner_id:
          type: string
          description: id of the owner
      example:
        title: producto generico
        price: 50
        stock: 10
        photo: photo.png
        _id: asd23124212
        owner_id: 1423sdasd2f

  responses:
    res201:
      description: Success response
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                description: Status code of the response
              response:
                $ref: '#/components/schemas/Product'
            example:
              statusCode: 201
              response:
                title: producto generico
                price: 50
                stock: 10
                photo: photo.png
                _id: asd23124212
                owner_id: 1423sdasd2f

    res401:
      description: Unauthorized response
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                description: Status code of the response
              message:
                type: string
                description: Error message
            example:
              statusCode: 401
              message: "Bad Auth!"

    res403:
      description: Forbidden response
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                description: Status code of the response
              message:
                type: string
                description: Error message
            example:
              statusCode: 403
              message: "Forbidden"

    res500:
      description: Internal Server Error response
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                description: Status code of the response
              message:
                type: string
                description: Error message
            example:
              statusCode: 500
              message: "POST /api/products/ products validation failed: title: Path `title` is required."

paths:
  /api/products:
    post: 
      summary: to create a product
      tags:
        - Products
      security:
        - cookieAuth: []
      requestBody:
        required: true
        description: data of the product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                statusCode: 201
                response:
                  title: producto generico
                  price: 50
                  stock: 10
                  photo: photo.png
                  _id: asd23124212
                  owner_id: 1423sdasd2f
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                    description: Status code of the response
                  message:
                    type: string
                    description: Error message
              example:
                statusCode: 401
                message: "Bad Auth!"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                    description: Status code of the response
                  message:
                    type: string
                    description: Error message
              example:
                statusCode: 403
                message: "Forbidden"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                    description: Status code of the response
                  message:
                    type: string
                    description: Error message
              example:
                statusCode: 500
                message: "POST /api/products/ products validation failed: title: Path `title` is required."

    get:
      summary: Get all products
      tags:
        - Products
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '401':
          $ref: '#/components/responses/res401'
        '403':
          $ref: '#/components/responses/res403'
        '500':
          $ref: '#/components/responses/res500'

  /api/products/{pid}:
    get:
      summary: Get a specific product
      tags:
        - Products
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: The ID of the product to retrieve
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                title: producto generico
                price: 50
                stock: 10
                photo: photo.png
                _id: asd23124212
                owner_id: 1423sdasd2f
        '401':
          $ref: '#/components/responses/res401'
        '403':
          $ref: '#/components/responses/res403'
        '500':
          $ref: '#/components/responses/res500'
    put:
      summary: Update a specific product
      tags:
        - Products
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: The ID of the product to update
      requestBody:
        required: true
        description: New data for the product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                title: producto generico
                price: 50
                stock: 10
                photo: photo.png
                _id: asd23124212
                owner_id: 1423sdasd2f
        '401':
          $ref: '#/components/responses/res401'
        '403':
          $ref: '#/components/responses/res403'
        '500':
          $ref: '#/components/responses/res500'
    delete:
      summary: Delete a specific product
      tags:
        - Products
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: The ID of the product to delete
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                title: producto generico
                price: 50
                stock: 10
                photo: photo.png
                _id: asd23124212
                owner_id: 1423sdasd2f
        '401':
          $ref: '#/components/responses/res401'
        '403':
          $ref: '#/components/responses/res403'
        '500':
          $ref: '#/components/responses/res500'
